/Library/Frameworks/Python.framework/Versions/3.8/bin/python3: can't open file '.tests_valid_conf.py': [Errno 2] No such file or directory
